modLoader = "javafml"
loaderVersion = "[21,)"
license = "MIT"

[[mods]]
modId = "fnafmod"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "logo.png"

[[dependencies.fnafmod]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"

[[dependencies.fnafmod]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
